name: Continuous Deployment to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/admin/projects/react_app
            git pull origin main
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            /home/admin/.nvm/versions/node/v23.3.0/bin/npm install
            /home/admin/.nvm/versions/node/v23.3.0/bin/npm run build
            sudo /bin/cp -r /home/admin/projects/react_app/build/* /var/www/html/portfolio.edicodesigns.com/
            sudo chown -R www-data:www-data /var/www/html/portfolio.edicodesigns.com/
            sudo chmod -R 755 /var/www/html/portfolio.edicodesigns.com/
            sudo systemctl restart nginx
            if [ $? -ne 0 ]; then
              echo "Nginx restart failed" >> /var/log/deploy-errors.log
              exit 1
            fi
            echo "Deployment completed"
